### ISSUE TITLE
Two drop animations at once

### ISSUE THREAD

**Issue by GabeJacobs** [daltoniam/DCAnimationKit#1]
When trying to do two drop animations at once on two different views, one of them drops, but the other fades.

This is on ios 8

**Comment by daltoniam** [comment]
Do both of the views have the same superview? The `UIDynamicAnimator` that gets created/called is attached to the view's superview. If they both have the same superview, this makes sense, as the `UIDynamicAnimator` class can't schedule 2 animations at once.

**Comment by GabeJacobs** [comment]
Hmmm...

How do you suggest getting around the issue? How do you do the animations in the readme where two views drop at once?

**Comment by daltoniam** [comment]
That is a good point, now I am second guessing myself :smile:. I honestly don't remember how I did that example, I will take a deeper look shortly. Might want to try changing line:

https://github.com/daltoniam/DCAnimationKit/blob/master/UIView%2BDCAnimationKit.m#L408

to:

``` objc
if(!animator.isRunning) {
        [animator removeAllBehaviors];
}
```

That code above is from the 0.0.1 tag, which is when I created the examples. It might be a bug I introduced in a later release (I just don't remember why I changed it now :confused: ). Let me know if that fixes and we can change it back or make it better.

**Comment by GabeJacobs** [comment]
Yep, that fixes it. Hm. Wonder if you ran into bugs or memory problems and that's why you changed it. I'll keep you updated.

**Comment by daltoniam** [comment]
Sweetness! Yeah I will see if I can find why I changed it. I vaguely remember it being an issue with chaining several animations back to back, but might have been some of my app code needs leaking into the library. Also thanks for sticking with the issue and proving my totally wrong with the `UIDynamicAnimator`. Not sure where I got it couldn't schedule 2 at a time :smile:.

**Comment by GabeJacobs** [comment]
That's what github is for!
